### ISSUE TITLE
[BUG] error on GPU

### ISSUE THREAD

**Issue by JunMa11** [kyegomez/MambaTransformer#3]
Thanks for sharing the awesome work.

I got the following error when running the example on GPU

```
python example.py
2024-01-13 21:46:44.846591: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-01-13 21:46:44.846624: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-01-13 21:46:44.848009: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-01-13 21:46:44.854341: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-01-13 21:46:45.757644: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
2024-01-13 21:46:47,012 - numexpr.utils - INFO - Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
2024-01-13 21:46:47,013 - numexpr.utils - INFO - NumExpr defaulting to 8 threads.
Traceback (most recent call last):
  File "/home/jma/Documents/sanity_test/mamba/mamba/MambaTransformer/example.py", line 17, in <module>
    out = model(x)
  File "/home/jma/Documents/sanity_test/mamba/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/jma/Documents/sanity_test/mamba/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/jma/Documents/sanity_test/mamba/mamba/MambaTransformer/mamba_transformer/model.py", line 213, in forward
    x = mamba(x) + x
  File "/home/jma/Documents/sanity_test/mamba/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/jma/Documents/sanity_test/mamba/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/jma/Documents/sanity_test/mamba/lib/python3.9/site-packages/zeta/nn/modules/simple_mamba.py", line 118, in forward
    y = self.ssm(x)
  File "/home/jma/Documents/sanity_test/mamba/lib/python3.9/site-packages/zeta/nn/modules/simple_mamba.py", line 158, in ssm
    y = self.selective_scan(
  File "/home/jma/Documents/sanity_test/mamba/lib/python3.9/site-packages/zeta/nn/modules/simple_mamba.py", line 205, in selective_scan
    x = deltaA[:, :, i] * x + deltaB_u[:, :, i]
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

```

**To Reproduce**

```
import torch
from mamba_transformer import MambaTransformer, MambaTransformerblock


x = torch.randn(10, 25, 512).to("cuda:0")
model = MambaTransformerblock(
    dim=512,
    heads=8,
    depth=4,
    dim_head=64,
    d_state=512,
    dropout=0.1,
    ff_mult=4
).to("cuda:0")

# # Pass the input tensor through the model and print the output shape
out = model(x)

print(f"{x.shape=}, {out.shape=}")
```

**Comment by kyegomez** [comment]
@JunMa11 so you're trying to run the model on cuda but there are other parts of the model running on the cpu, the problem comes from the modules inside MambaTransformer.

I can fix this by making it more customize-able, until then you can keep trying things out.

**Comment by aviralchharia** [comment]
Hi @JunMa11, did you figure out how to solve this? I am facing exactly same problem. I want to use the cuda
